name: First Github Action

on: [pull_request]

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Say Hello
        run: echo "Hello, World!"
